import { useState } from "react";
import { GraduationCap, BrainCircuit, Target, ChartNoAxesCombined, ShieldCheck, ArrowRight } from "lucide-react";
function RegistrationForm({ onContinue }) {
 const [formData,setFormData]=useState({fullName:"",email:"",phone:"",collegeId:"",branch:"",password:"",confirmPassword:""});const[errors,setErrors]=useState({});
 const handleChange=e=>{const{name,value}=e.target;setFormData(current=>({...current,[name]:value}));setErrors(current=>({...current,[name]:""}));};
 const validateForm=()=>{const next={};if(!formData.fullName.trim())next.fullName="Full name is required";if(!formData.email.trim())next.email="Email is required";else if(!/\S+@\S+\.\S+/.test(formData.email))next.email="Enter a valid email address";if(!formData.phone.trim())next.phone="Phone number is required";else if(!/^[0-9]{10}$/.test(formData.phone))next.phone="Enter a valid 10-digit phone number";if(!formData.collegeId.trim())next.collegeId="College ID is required";if(!formData.branch)next.branch="Please select your branch";if(formData.password.length<8)next.password="Use at least 8 characters";if(formData.confirmPassword!==formData.password)next.confirmPassword="Passwords do not match";setErrors(next);return Object.keys(next).length===0;};
 const handleSubmit=e=>{e.preventDefault();if(!validateForm())return;onContinue(formData);};
 const field=(label,name,placeholder,type="text",full=false,autoComplete)=> <div className={`form-group ${full?"full-width":""}`}><label htmlFor={name}>{label}</label><input id={name} type={type} name={name} value={formData[name]} onChange={handleChange} placeholder={placeholder} autoComplete={autoComplete}/>{errors[name]&&<small className="error">{errors[name]}</small>}</div>;
 return <div className="registration-page"><div className="registration-card">
 <aside className="registration-header"><div className="brand-lockup"><div className="logo-circle"><GraduationCap size={27}/></div><div className="brand-words"><h1>CAMPUSLINK</h1><p>ECOSYSTEM</p></div></div><h2 className="brand-quote">Your journey from campus to career starts here.</h2><div className="benefit-list"><div><span><BrainCircuit size={20}/></span><div><b>AI Readiness Analysis</b><small>Understand your technical, academic, and interview readiness.</small></div></div><div><span><Target size={20}/></span><div><b>Smart Job Matching</b><small>Discover relevant roles and see your skill gaps clearly.</small></div></div><div><span><ChartNoAxesCombined size={20}/></span><div><b>Placement Tracking</b><small>Follow every step from application through joining.</small></div></div></div><div className="security-note"><ShieldCheck size={17}/> Campus verified · Secure account setup</div></aside>
 <div className="registration-main"><div className="registration-kicker"><span><i>✧</i> Student onboarding</span><small>Already have an account? <button type="button">Log in</button></small></div><div className="registration-title"><h2>Create Your CAMPUSLINK Account</h2><p>Join your campus placement ecosystem and get AI-powered career insights.</p></div><div className="progress-container"><div className="progress-step active"><div className="step-number">1</div><span>Registration</span></div><div className="progress-line"/><div className="progress-step"><div className="step-number">2</div><span>Email OTP</span></div><div className="progress-line"/><div className="progress-step"><div className="step-number">3</div><span>Dashboard</span></div></div>
 <form onSubmit={handleSubmit} noValidate><div className="form-grid">{field("Student name","fullName","Enter your full name","text",true,"name")}{field("Email ID","email","student@example.com","email",false,"email")}{field("College ID","collegeId","Enter your college ID")}{field("Student phone number","phone","+91  XXXXX XXXXX","tel",false,"tel")}<div className="form-group"><label htmlFor="branch">Branch</label><select id="branch" name="branch" value={formData.branch} onChange={handleChange}><option value="">Select your branch</option>{["Computer Science","Information Technology","Electronics","Electrical","Mechanical","Civil","Other"].map(x=><option key={x}>{x}</option>)}</select>{errors.branch&&<small className="error">{errors.branch}</small>}</div>{field("Password","password","Minimum 8 characters","password",false,"new-password")}{field("Confirm password","confirmPassword","Re-enter password","password",false,"new-password")}</div><div className="otp-info"><b>Email OTP</b><p>Demo flow: use code 123456 on the next step.</p></div><button type="submit" className="continue-btn">Create account <ArrowRight size={18}/></button></form><div className="login-text">By continuing, you agree to our student account terms.</div></div></div></div>;
}
export default RegistrationForm;
